# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#>.

`RDF-LinkedData-RWHypermedia`
    :test-requirement       [ :on "Test::More 0.96"^^:CpanId ];
    :test-requirement       [ :on "Test::RDF 1.21"^^:CpanId ];
    :runtime-requirement    [ :on "Moo"^^:CpanId ];
    :runtime-requirement    [ :on "RDF::LinkedData"^^:CpanId ];
#    :runtime-requirement    [ :on "RDF::ACL"^^:CpanId ];
    :develop-recommendation [ :on "Dist::Inkt 0.001"^^:CpanId ];
    .

